version: '3.8'

services:
  simulator:
    container_name: udp_server
    image: ghcr.io/laendleenergy/udp_server:latest
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=4433
      - MQTT_BROKER_PORT=1884
      - MQTT_BROKER_ADDRESS=85.215.60.151
    ports:
      - "4433:4433/tcp"
      - "4433:4433/udp"